definitions:
  dto.CreateRewardPayloadDTO:
    properties:
      recipient_address:
        type: string
      token_amount:
        type: string
    type: object
  dto.MembershipEventsDTO:
    properties:
      amount:
        type: string
      end_duration:
        type: string
      id:
        type: integer
      order_id:
        type: integer
      status:
        type: integer
      transaction_hash:
        type: string
      user_address:
        type: string
    type: object
  util.GeneralError:
    properties:
      code:
        description: HTTP error code, or custom error code
        type: integer
      errors:
        description: List of error send server 2 server
        items:
          type: string
        type: array
      string:
        description: Friendly error message
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/membership:
    get:
      consumes:
      - application/json
      description: Get membership event by order ID
      parameters:
      - description: Order ID to query
        in: query
        name: orderId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.MembershipEventsDTO'
        "400":
          description: Invalid Order ID
          schema:
            $ref: '#/definitions/util.GeneralError'
        "404":
          description: Membership event not found
          schema:
            $ref: '#/definitions/util.GeneralError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/util.GeneralError'
      summary: Get membership event by order ID
      tags:
      - membership
  /api/v1/rewards:
    post:
      consumes:
      - application/json
      description: Reward
      parameters:
      - description: Request reward tokens, required
        in: body
        name: payload
        required: true
        schema:
          items:
            $ref: '#/definitions/dto.CreateRewardPayloadDTO'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: 'When success, return {"success": true}'
          schema:
            items:
              $ref: '#/definitions/dto.CreateRewardPayloadDTO'
            type: array
        "400":
          description: Invalid payload
          schema:
            $ref: '#/definitions/util.GeneralError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/util.GeneralError'
      summary: Reward
      tags:
      - reward
swagger: "2.0"
