definitions:
  dto.CreateRewardPayloadDTO:
    properties:
      recipient_address:
        type: string
      token_amount:
        type: string
    type: object
  util.GeneralError:
    properties:
      code:
        description: HTTP error code, or custom error code
        type: integer
      errors:
        description: List of error send server 2 server
        items:
          type: string
        type: array
      string:
        description: Friendly error message
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/rewards:
    post:
      consumes:
      - application/json
      description: Reward
      parameters:
      - description: Request reward tokens, required
        in: body
        name: payload
        required: true
        schema:
          items:
            $ref: '#/definitions/dto.CreateRewardPayloadDTO'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: 'When success, return {"success": true}'
          schema:
            items:
              $ref: '#/definitions/dto.CreateRewardPayloadDTO'
            type: array
        "417":
          description: Expectation Failed
          schema:
            $ref: '#/definitions/util.GeneralError'
        "424":
          description: Failed Dependency
          schema:
            $ref: '#/definitions/util.GeneralError'
      summary: Reward
      tags:
      - reward
swagger: "2.0"
